# Dockerfile.backend
FROM python:3.12-slim

WORKDIR /app

COPY code/backend/dist/game_backend-0.1.2-py3-none-any.whl .

RUN pip install --no-cache-dir game_backend-0.1.2-py3-none-any.whl

CMD ["python3", "-m", "game_backend"]